server:
  port: 8889
spring:
  application:
    name: config-server1
  cloud:
    config:
      server:
        git:
          uri:
          password:
          username:
          search-paths: config1 # 多个目录以逗号分隔